languageCode: "en-gb"
baseUrl: "https://blog.blah.cloud"
title: "Blah, Cloud"
theme: "anubis"
paginate: 10
disqusShortname: "yourdiscussshortname"
googleAnalytics: "G-12345"
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0

params:
  author: "Myles Gray"
  email: myles@blah.cloud # used for microformats
  avatar: "/images/me.jpg" # used for microformats
  description: "Wants to know how to build everything, to a fault."
  # Uncomment if you need this
  # images:
  #   - images/og-featured.png # relative path to "static" directory
  # customCSS:
  #   - css/my.css # relative path to "assets" directory (don't use main.css filename)
  # customJS:
  #   - js/main.js # relative path to "assets" directory
  dateFormat: "2006-01-02"
  paginationSinglePost: false
  style: auto
  readMore: false
  disableSummary: false
  # # utteranc.es support
  # utterancesRepo: ""  # mandatory
  # utterancesTheme: "" # optional
  # utterancesIssue: "" # optional
  # utterancesLabel: "" # optional
  # webmentions:
  #   url: https://blog.blah.cloud/webemntions/receive
  #   login: hugo-theme-anubis
  #   pingback: true
  social:
  - id: github
    name: mylesagray
  - id: twitter
    name: mylesagray
