baseURL: "https://beta.blah.cloud/"
title: Blah, Cloud
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Blah, Cloud
    description: "Adventures in architectures"
    keywords: [Blog, Portfolio, Infrastructure, Cloud]
    author: Myles Gray
    images: ["/images/logo-text.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto
    disableThemeToggle: false

    ShowReadingTime: false
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowPostRelatedContent: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: true
    hidemeta: false
    hideSummary: false
    ShowToc: true
    tocopen: false

    assets:
        disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: /images/favicon.ico
        favicon16x16: /images/favicon-16x16.png
        favicon32x32: /images/favicon-32x32.png
        apple_touch_icon: /images/apple-touch-icon.png
        safari_pinned_tab: /images/logo.png

    label:
        text: "Blah, Cloud."
        icon: /images/logo-title.png
        iconHeight: 40

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Myles Gray
        subtitle: "DevOps Magician"
        imageUrl: "/images/me.jpg"
        imageWidth: 250
        imageHeight: 250
        imageTitle: Myles Gray
        buttons:
            - name: Posts
              url: blog
            - name: Search
              url: search

    # # home-info mode
    # homeInfoParams:
    #     Title: "Myles Gray"
    #     Content: >
    #         DevOps Magician, CI/CD Hipster

    socialIcons:
        - name: twitter
          url: "https://twitter.com/mylesagray"
        - name: github
          url: "https://github.com/mylesagray"
        - name: linkedin
          url: "https://www.linkedin.com/in/mylesgray"
        - name: RSS
          url: "index.xml"

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"
    #     bing:
    #         SiteVerificationTag: "XYZabc"
    #     yandex:
    #         SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page
        linkFullImages: false

    editPost:
        URL: "https://github.com/mylesagray/blog/blob/master/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.3
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: blog
          name: blog
          url: /blog/
          weight: 10
        - identifier: works
          name: works
          url: /works/
          weight: 20
        - identifier: about
          name: about
          url: /about/
          weight: 30
        - identifier: search
          pre: '<svg style="height:1em; margin-top:1.5em" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="search" class="fill-current w-5" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512">
                            <path d="M505 442.7L405.3 343c-4.5-4.5-10.6-7-17-7H372c27.6-35.3 44-79.7 44-128C416 93.1 322.9 0 208 0S0 93.1 0 208s93.1 208 208 208c48.3 0 92.7-16.4 128-44v16.3c0 6.4 2.5 12.5 7 17l99.7 99.7c9.4 9.4 24.6 9.4 33.9 0l28.3-28.3c9.4-9.4 9.4-24.6.1-34zM208 336c-70.7 0-128-57.2-128-128 0-70.7 57.2-128 128-128 70.7 0 128 57.2 128 128 0 70.7-57.2 128-128 128z"></path>
                        </svg>'
          url: /search/
          weight: 40

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
    highlight:
        codeFences: true
        #hl_Lines: ""
        #lineNoStart: 1
        lineNos: false
        lineNumbersInTable: true
        noClasses: false
        #tabWidth: 4
        guessSyntax: true

taxonomies:
  category: categories
  tag: tags
  series: series

outputs:
    home:
        - HTML
        - RSS
        - JSON
        - AMP
    page:
        - HTML
        - AMP

privacy:
  youtube:
    privacyEnhanced: true

related:
  includeNewer: true
  indices:
  - name: series
    weight: 200
  - name: tags
    weight: 100
  - name: categories
    weight: 50
  - name: date
    weight: 10
  threshold: 30
  toLower: true