template: opengraph/template.png
title:
  start:
    px: 113
    py: 150
  fgHexColor: "#4D4E4C"
  fontSize: 56
  fontStyle: Bold
  maxWidth: 680
  lineSpacing: 10
category:
  start:
    px: 810
    py: 430
  fgHexColor: "#E9C566"
  fontSize: 30
  fontStyle: Regular
info:
  start:
    px: 113
    py: 100
  fgHexColor: "#636463"
  fontSize: 38
  fontStyle: Regular
  separator: " - "
tags:
  start:
    px: 113
    py: 500
  fgHexColor: "#FFFFFF"
  bgHexColor: "#4D4E4C"
  fontSize: 22
  fontStyle: Medium
  boxAlign: Left
  boxSpacing: 6
  boxPadding:
    top: 6
    right: 10
    bottom: 6
    left: 8