name: github pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v6
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: https://github.com/peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Copy to branch
        uses: https://github.com/peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: pages
          force_orphan: true

      - name: Deploy
        uses: https://code.forgejo.org/actions/git-pages@v2
        with:
          site: https://blah.cloud
          server: grebedoc.dev
          password: ${{ secrets.SITE_PASSWORD }}
          source: public/